name: Go Test

on: push

jobs:
  build-test-publish:
    name: Go Build, Test and publish container
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14.10
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.10
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -v .

      - name: Go Test
        run: go test -v ./...

      - name: Test '/api/news' JSON Endpoint
        run: hack/test_json_api.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/codemanufaktur/web-cli:latest
            ghcr.io/codemanufaktur/web-cli:1.0.0-beta